services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: culture_compass
      POSTGRES_PASSWORD: "2QcNIVA_UPIpZ3Wl5DPFI9wKtDOkuD-v"
    volumes:
      - culture_compass_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "6lGOovnhy-lczdvl09GVgt3onPfvJvD4"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: culture_compass_test
      POSTGRES_PASSWORD: "LjtNpq_AIn1-pIC8Iubz5K1eD0jnFbCa"
    volumes:
      - culture_compass_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "m3VUKnfXd24UJRqRCIh9pQ7bWGfLG5t5"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  culture_compass_data:
  culture_compass_test_data:
